plugins:
  hacker_news_client_enabled:
    default: false
    client: false
  hacker_news_client_top_stories_count:
    default: 30
    min: 1
    max: 100
    client: false
  hacker_news_client_fetch_articles:
    default: true
    client: false
